#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluetech.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PatentiLookUp")]
	public partial class LookupDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definizioni metodo Extensibility
    partial void OnCreated();
    partial void InsertAnagrafiche(Anagrafiche instance);
    partial void UpdateAnagrafiche(Anagrafiche instance);
    partial void DeleteAnagrafiche(Anagrafiche instance);
    partial void InsertProgressivi(Progressivi instance);
    partial void UpdateProgressivi(Progressivi instance);
    partial void DeleteProgressivi(Progressivi instance);
    partial void InsertPratiche(Pratiche instance);
    partial void UpdatePratiche(Pratiche instance);
    partial void DeletePratiche(Pratiche instance);
    #endregion
		
		public LookupDatabaseDataContext() : 
				base(global::Pot.DataLayer.Properties.Settings.Default.PatentiLookUpConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LookupDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LookupDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LookupDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LookupDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Anagrafiche> Anagrafiche
		{
			get
			{
				return this.GetTable<Anagrafiche>();
			}
		}
		
		public System.Data.Linq.Table<Progressivi> Progressivi
		{
			get
			{
				return this.GetTable<Progressivi>();
			}
		}
		
		public System.Data.Linq.Table<Pratiche> Pratiche
		{
			get
			{
				return this.GetTable<Pratiche>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Anagrafiche")]
	public partial class Anagrafiche : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodiceEsterno;
		
		private string _CodiceMexal;
		
		private System.Nullable<bool> _IsMedico;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceEsternoChanging(string value);
    partial void OnCodiceEsternoChanged();
    partial void OnCodiceMexalChanging(string value);
    partial void OnCodiceMexalChanged();
    partial void OnIsMedicoChanging(System.Nullable<bool> value);
    partial void OnIsMedicoChanged();
    #endregion
		
		public Anagrafiche()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceEsterno", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodiceEsterno
		{
			get
			{
				return this._CodiceEsterno;
			}
			set
			{
				if ((this._CodiceEsterno != value))
				{
					this.OnCodiceEsternoChanging(value);
					this.SendPropertyChanging();
					this._CodiceEsterno = value;
					this.SendPropertyChanged("CodiceEsterno");
					this.OnCodiceEsternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceMexal", DbType="VarChar(50)")]
		public string CodiceMexal
		{
			get
			{
				return this._CodiceMexal;
			}
			set
			{
				if ((this._CodiceMexal != value))
				{
					this.OnCodiceMexalChanging(value);
					this.SendPropertyChanging();
					this._CodiceMexal = value;
					this.SendPropertyChanged("CodiceMexal");
					this.OnCodiceMexalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMedico", DbType="Bit")]
		public System.Nullable<bool> IsMedico
		{
			get
			{
				return this._IsMedico;
			}
			set
			{
				if ((this._IsMedico != value))
				{
					this.OnIsMedicoChanging(value);
					this.SendPropertyChanging();
					this._IsMedico = value;
					this.SendPropertyChanged("IsMedico");
					this.OnIsMedicoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Progressivi")]
	public partial class Progressivi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NomeContatore;
		
		private long _Progressivo;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNomeContatoreChanging(string value);
    partial void OnNomeContatoreChanged();
    partial void OnProgressivoChanging(long value);
    partial void OnProgressivoChanged();
    #endregion
		
		public Progressivi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeContatore", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NomeContatore
		{
			get
			{
				return this._NomeContatore;
			}
			set
			{
				if ((this._NomeContatore != value))
				{
					this.OnNomeContatoreChanging(value);
					this.SendPropertyChanging();
					this._NomeContatore = value;
					this.SendPropertyChanged("NomeContatore");
					this.OnNomeContatoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Progressivo", DbType="BigInt NOT NULL")]
		public long Progressivo
		{
			get
			{
				return this._Progressivo;
			}
			set
			{
				if ((this._Progressivo != value))
				{
					this.OnProgressivoChanging(value);
					this.SendPropertyChanging();
					this._Progressivo = value;
					this.SendPropertyChanged("Progressivo");
					this.OnProgressivoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pratiche")]
	public partial class Pratiche : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodicePratica;
		
		private string _CodiceCliente;
		
		private string _CodiceMedico;
		
		private string _CodiceMedicoEsito;
		
		private string _Esito;
		
		private System.Nullable<int> _TipoPagamento;
		
		private System.Nullable<int> _ImportoMedico;
		
		private System.Nullable<int> _ImportoSconto;
		
		private System.Nullable<int> _Importo;
		
		private string _NumeroFattura;
		
		private string _DataFattura;
		
		private string _NumeroPagamento;
		
		private string _NumeroPagamentoMedico;
		
		private string _DataPagamentoMedico;
		
		private string _NumeroNotaCredito;
		
		private string _DataNotaCredito;
		
		private string _NumeroStorno;
		
		private string _DataStorno;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodicePraticaChanging(string value);
    partial void OnCodicePraticaChanged();
    partial void OnCodiceClienteChanging(string value);
    partial void OnCodiceClienteChanged();
    partial void OnCodiceMedicoChanging(string value);
    partial void OnCodiceMedicoChanged();
    partial void OnCodiceMedicoEsitoChanging(string value);
    partial void OnCodiceMedicoEsitoChanged();
    partial void OnEsitoChanging(string value);
    partial void OnEsitoChanged();
    partial void OnTipoPagamentoChanging(System.Nullable<int> value);
    partial void OnTipoPagamentoChanged();
    partial void OnImportoMedicoChanging(System.Nullable<int> value);
    partial void OnImportoMedicoChanged();
    partial void OnImportoScontoChanging(System.Nullable<int> value);
    partial void OnImportoScontoChanged();
    partial void OnImportoChanging(System.Nullable<int> value);
    partial void OnImportoChanged();
    partial void OnNumeroFatturaChanging(string value);
    partial void OnNumeroFatturaChanged();
    partial void OnDataFatturaChanging(string value);
    partial void OnDataFatturaChanged();
    partial void OnNumeroPagamentoChanging(string value);
    partial void OnNumeroPagamentoChanged();
    partial void OnNumeroPagamentoMedicoChanging(string value);
    partial void OnNumeroPagamentoMedicoChanged();
    partial void OnDataPagamentoMedicoChanging(string value);
    partial void OnDataPagamentoMedicoChanged();
    partial void OnNumeroNotaCreditoChanging(string value);
    partial void OnNumeroNotaCreditoChanged();
    partial void OnDataNotaCreditoChanging(string value);
    partial void OnDataNotaCreditoChanged();
    partial void OnNumeroStornoChanging(string value);
    partial void OnNumeroStornoChanged();
    partial void OnDataStornoChanging(string value);
    partial void OnDataStornoChanged();
    #endregion
		
		public Pratiche()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodicePratica", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodicePratica
		{
			get
			{
				return this._CodicePratica;
			}
			set
			{
				if ((this._CodicePratica != value))
				{
					this.OnCodicePraticaChanging(value);
					this.SendPropertyChanging();
					this._CodicePratica = value;
					this.SendPropertyChanged("CodicePratica");
					this.OnCodicePraticaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceCliente", DbType="VarChar(50)")]
		public string CodiceCliente
		{
			get
			{
				return this._CodiceCliente;
			}
			set
			{
				if ((this._CodiceCliente != value))
				{
					this.OnCodiceClienteChanging(value);
					this.SendPropertyChanging();
					this._CodiceCliente = value;
					this.SendPropertyChanged("CodiceCliente");
					this.OnCodiceClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceMedico", DbType="VarChar(50)")]
		public string CodiceMedico
		{
			get
			{
				return this._CodiceMedico;
			}
			set
			{
				if ((this._CodiceMedico != value))
				{
					this.OnCodiceMedicoChanging(value);
					this.SendPropertyChanging();
					this._CodiceMedico = value;
					this.SendPropertyChanged("CodiceMedico");
					this.OnCodiceMedicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceMedicoEsito", DbType="VarChar(50)")]
		public string CodiceMedicoEsito
		{
			get
			{
				return this._CodiceMedicoEsito;
			}
			set
			{
				if ((this._CodiceMedicoEsito != value))
				{
					this.OnCodiceMedicoEsitoChanging(value);
					this.SendPropertyChanging();
					this._CodiceMedicoEsito = value;
					this.SendPropertyChanged("CodiceMedicoEsito");
					this.OnCodiceMedicoEsitoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Esito", DbType="VarChar(50)")]
		public string Esito
		{
			get
			{
				return this._Esito;
			}
			set
			{
				if ((this._Esito != value))
				{
					this.OnEsitoChanging(value);
					this.SendPropertyChanging();
					this._Esito = value;
					this.SendPropertyChanged("Esito");
					this.OnEsitoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoPagamento", DbType="Int")]
		public System.Nullable<int> TipoPagamento
		{
			get
			{
				return this._TipoPagamento;
			}
			set
			{
				if ((this._TipoPagamento != value))
				{
					this.OnTipoPagamentoChanging(value);
					this.SendPropertyChanging();
					this._TipoPagamento = value;
					this.SendPropertyChanged("TipoPagamento");
					this.OnTipoPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportoMedico", DbType="Int")]
		public System.Nullable<int> ImportoMedico
		{
			get
			{
				return this._ImportoMedico;
			}
			set
			{
				if ((this._ImportoMedico != value))
				{
					this.OnImportoMedicoChanging(value);
					this.SendPropertyChanging();
					this._ImportoMedico = value;
					this.SendPropertyChanged("ImportoMedico");
					this.OnImportoMedicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportoSconto", DbType="Int")]
		public System.Nullable<int> ImportoSconto
		{
			get
			{
				return this._ImportoSconto;
			}
			set
			{
				if ((this._ImportoSconto != value))
				{
					this.OnImportoScontoChanging(value);
					this.SendPropertyChanging();
					this._ImportoSconto = value;
					this.SendPropertyChanged("ImportoSconto");
					this.OnImportoScontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Importo", DbType="Int")]
		public System.Nullable<int> Importo
		{
			get
			{
				return this._Importo;
			}
			set
			{
				if ((this._Importo != value))
				{
					this.OnImportoChanging(value);
					this.SendPropertyChanging();
					this._Importo = value;
					this.SendPropertyChanged("Importo");
					this.OnImportoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFattura", DbType="VarChar(50)")]
		public string NumeroFattura
		{
			get
			{
				return this._NumeroFattura;
			}
			set
			{
				if ((this._NumeroFattura != value))
				{
					this.OnNumeroFatturaChanging(value);
					this.SendPropertyChanging();
					this._NumeroFattura = value;
					this.SendPropertyChanged("NumeroFattura");
					this.OnNumeroFatturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataFattura", DbType="VarChar(50)")]
		public string DataFattura
		{
			get
			{
				return this._DataFattura;
			}
			set
			{
				if ((this._DataFattura != value))
				{
					this.OnDataFatturaChanging(value);
					this.SendPropertyChanging();
					this._DataFattura = value;
					this.SendPropertyChanged("DataFattura");
					this.OnDataFatturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPagamento", DbType="VarChar(50)")]
		public string NumeroPagamento
		{
			get
			{
				return this._NumeroPagamento;
			}
			set
			{
				if ((this._NumeroPagamento != value))
				{
					this.OnNumeroPagamentoChanging(value);
					this.SendPropertyChanging();
					this._NumeroPagamento = value;
					this.SendPropertyChanged("NumeroPagamento");
					this.OnNumeroPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroPagamentoMedico", DbType="VarChar(50)")]
		public string NumeroPagamentoMedico
		{
			get
			{
				return this._NumeroPagamentoMedico;
			}
			set
			{
				if ((this._NumeroPagamentoMedico != value))
				{
					this.OnNumeroPagamentoMedicoChanging(value);
					this.SendPropertyChanging();
					this._NumeroPagamentoMedico = value;
					this.SendPropertyChanged("NumeroPagamentoMedico");
					this.OnNumeroPagamentoMedicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataPagamentoMedico", DbType="VarChar(50)")]
		public string DataPagamentoMedico
		{
			get
			{
				return this._DataPagamentoMedico;
			}
			set
			{
				if ((this._DataPagamentoMedico != value))
				{
					this.OnDataPagamentoMedicoChanging(value);
					this.SendPropertyChanging();
					this._DataPagamentoMedico = value;
					this.SendPropertyChanged("DataPagamentoMedico");
					this.OnDataPagamentoMedicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroNotaCredito", DbType="VarChar(50)")]
		public string NumeroNotaCredito
		{
			get
			{
				return this._NumeroNotaCredito;
			}
			set
			{
				if ((this._NumeroNotaCredito != value))
				{
					this.OnNumeroNotaCreditoChanging(value);
					this.SendPropertyChanging();
					this._NumeroNotaCredito = value;
					this.SendPropertyChanged("NumeroNotaCredito");
					this.OnNumeroNotaCreditoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNotaCredito", DbType="VarChar(50)")]
		public string DataNotaCredito
		{
			get
			{
				return this._DataNotaCredito;
			}
			set
			{
				if ((this._DataNotaCredito != value))
				{
					this.OnDataNotaCreditoChanging(value);
					this.SendPropertyChanging();
					this._DataNotaCredito = value;
					this.SendPropertyChanged("DataNotaCredito");
					this.OnDataNotaCreditoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroStorno", DbType="VarChar(50)")]
		public string NumeroStorno
		{
			get
			{
				return this._NumeroStorno;
			}
			set
			{
				if ((this._NumeroStorno != value))
				{
					this.OnNumeroStornoChanging(value);
					this.SendPropertyChanging();
					this._NumeroStorno = value;
					this.SendPropertyChanged("NumeroStorno");
					this.OnNumeroStornoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataStorno", DbType="VarChar(50)")]
		public string DataStorno
		{
			get
			{
				return this._DataStorno;
			}
			set
			{
				if ((this._DataStorno != value))
				{
					this.OnDataStornoChanging(value);
					this.SendPropertyChanging();
					this._DataStorno = value;
					this.SendPropertyChanged("DataStorno");
					this.OnDataStornoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
